### ISSUE TITLE
Support for other database servers?

### ISSUE THREAD

**Issue by hopla** [Shuttle/Shuttle.Esb.SqlServer#5]
Can I use this assembly to run the subscription service on other database servers, by supplying a different ADO.NET data provider with the connection-string (e.g. NPgSql)?
Looking at the code this should work, right?

**Comment by eben-roux** [comment]
I'm not quite sure if it will work.  If it doesn't you could always create your own implementation.  I'd be happy to help where I can although I do not have any experience with PostgreSQL.  A pull request would always be appreciated :) --- well, I'd probably have to create a repo first...

**Comment by hopla** [comment]
OK, I'll experiment a bit. 
My expectation is that just overriding the sql scripts should be enough.

If I decide to create a Shuttle.Data.Postgress assembly, I'll be sure to send you a pull request!

**Comment by eben-roux** [comment]
Actually, you may be onto something... I forgot about that.

If the only change is going to be the scripts you could actually place them in some folder with the same names and, using configuration, specify the folder to load the scripts from.  If a particular script isn't found the default is loaded from the included content.
